## Tensorの基礎

In [75]:
import torch
import numpy as np
torch.manual_seed(42)

In [4]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [5]:
type(tensor_from_list)

torch.Tensor

In [6]:
tensor_from_list.dtype

torch.int64

In [7]:
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [8]:
tensor_from_list.dtype

torch.float32

In [12]:
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

#### ↑tensorはデフォルトだと32bit。64bitにしたい場合は変換する必要がある

In [13]:
zeros_tensor = torch.zeros((2, 3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
eye_tensor = torch.eye(3)
eye_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [21]:
random_tensor = torch.rand((2, 3))
random_tensor

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [23]:
# NumPyとの対応
np_zeros = np.zeros((2, 3))
np_ones = np.ones((2, 3))
np_eye = np.eye(3)
np_random = np.random.rand(2, 3)
print(np_zeros, np_zeros.dtype)
print(np_ones, np_ones.dtype)
print(np_eye, np_eye.dtype)
print(np_random, np_random.dtype)

[[0. 0. 0.]
 [0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]] float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64
[[0.31933051 0.5349442  0.2626178 ]
 [0.41915441 0.79223796 0.74039971]] float64


#### NumPyはデフォルトがfloat32なのでtensorと異なる。バグの原因になるかもしれないので覚えておく。

In [24]:
zeros_tensor.shape

torch.Size([2, 3])

In [26]:
np_zeros.shape

(2, 3)

## Tensorの操作

In [28]:
tensor_example = torch.rand((2, 3, 4))
np_example = np.random.rand(2, 3, 4)
print(tensor_example, np_example)

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]]) [[[0.8653761  0.83325345 0.31467432 0.45379041]
  [0.96549829 0.64978504 0.31688399 0.61049912]
  [0.82134748 0.18525031 0.00839028 0.25210285]]

 [[0.01117994 0.9280193  0.62146795 0.84304781]
  [0.30742377 0.04952779 0.67097861 0.10529921]
  [0.93741591 0.3639327  0.85164014 0.26615855]]]


In [29]:
tensor_example.shape

torch.Size([2, 3, 4])

In [30]:
np_example.shape

(2, 3, 4)

In [35]:
# 転置
permuted_tensor = torch.permute(tensor_example, (1, 0, 2))
transposed_np = np.transpose(np_example, (1, 0, 2))
print(permuted_tensor.shape)
print(transposed_np.shape)

transposed_tensor = torch.transpose(tensor_example, 0, 1)
print(transposed_tensor.shape)

# 2次元（rankが2つのtensor）の場合は.Tや.t()で転置することができる

torch.Size([3, 2, 4])
(3, 2, 4)
torch.Size([3, 2, 4])


In [37]:
# reshape
reshaped_tensor = torch.reshape(tensor_example, (6, 4))
reshaped_np = np.reshape(np_example, (6, 4))
print(reshaped_tensor.shape)
print(reshaped_np.shape)

torch.Size([6, 4])
(6, 4)


In [38]:
reshaped_tensor[0] = 0
reshaped_tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

In [39]:
tensor_example

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

#### ↑reshapeは基本的にはコピーではなく、同じメモリを使用し元々の変数にアクセスするため、reshape後の変数を変更すると元々の変数も変更される

In [43]:
# メモリが連続でなければreshapeはコピーを返す
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(x)
print(x.T)
y = x.T

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 3, 5],
        [2, 4, 6]])


In [45]:
# 連続なメモリに保存されていない
y.is_contiguous() #連続→Trueを返す

False

In [46]:
x.is_contiguous()

True

In [47]:
z = y.reshape(-1)

In [51]:
z[0] = 0
z

tensor([0, 3, 5, 2, 4, 6])

In [52]:
y

tensor([[1, 3, 5],
        [2, 4, 6]])

#### ↑zは連続でないのでreshapeでコピーを返しているため、yには影響がない

In [53]:
z = y.view(-1)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

#### ↑.view()は連続の場合のみreshapeし、連続でない場合はエラーを返すのでtensorを無駄に増やすことを防ぐことができる

In [56]:
# flatten
flattened_tensor = torch.flatten(tensor_example)
flattened_np = np_example.flatten
print(flattened_tensor.shape)
print(flattened_np.shape)

torch.Size([24])


AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [58]:
# suqueeze
tensor_example = torch.tensor([[[1], [2], [3]]])
np_example = np.array([[[1], [2], [3]]])
print(tensor_example.shape)
print(np_example.shape)

torch.Size([1, 3, 1])
(1, 3, 1)


In [62]:
squeezed_tensor = torch.squeeze(tensor_example)
squeezed_np = np.squeeze(np_example)
print(squeezed_tensor.shape)
print(squeezed_np.shape)

torch.Size([3])
(3,)


In [65]:
unsqueezed_tensor = torch.unsqueeze(tensor_example, 0)
expand_dims_np = np.expand_dims(np_example, 0)
print(unsqueezed_tensor.shape)
print(expand_dims_np.shape)

torch.Size([1, 1, 3, 1])
(1, 1, 3, 1)


In [71]:
tensor_example[None, :, :, :].shape

torch.Size([1, 1, 3, 1])

#### ↑この書き方でもランクを増加させることができる

### Tensorの便利関数

In [77]:
tensor_example = torch.rand((2, 3))
np_example = np.random.rand(2, 3)
print(tensor_example)
print(np_example)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
[[0.54130167 0.87443459 0.20558393]
 [0.91331984 0.41040014 0.00628511]]


In [74]:
# 合計
print(torch.sum(tensor_example))
print(np.sum(np_example))

tensor(2.2878)
2.9496135360571576


### 以下同様

### データ型をtensorではなく数値で取得したい場合は、.item()を使用する